version: "3"
services:
  service1:
    build:
      context: ./Service1
    ports: 
      - 8199:8199
    networks:
      - backend
  service2:
    build:
      context: ./Service2
    # command: python manage.py runserver 0.0.0.0:8000
    ports: 
      - 8200:8200
    networks:
      - backend
    depends_on:
      - service1  
networks:
  backend: